# Generated by Django 4.1.2 on 2026-01-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_award_projectcategory_stat_project_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['-issue_date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-featured', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='award',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='award',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='education',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='education',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='award',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='education',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
